language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Um3ARQFLUZyvrkpqllsnziDpacj7OgL7gbMByUZ0D4waameG+jnZt5UStwQgJN1mKQIuAYecfRKT2CU20fVGIz2hztP0wZ+/zFnCsQa9gLAbLWOuXPG7mPHSURyYNzhvnAoz3nycmQdlnuOWGANoV70RjIT5phy0kM1zL6VpRjyaU/FLExBNnauxhyollIJ6mGthL1YDdwmlE0kV6GZ911lHhHTX4g8wR+P6T/WwVHwzTbsaCppsSWzZbRICsoOV0uo7YXLQ9+5ngjyxISfe1rhCDxXsOhKHkQEJAJRYdqvSN63FzTLaNde4/Q7NESlNZNDMNbEuUD/rq10zM+xffgNnv00rvNnRF5rUAy1gBp2cWqlFFqxfg1BxTJ9o/p2krAen7iijVyQpS7Xm8ege5XDDgqEBhcnvsg1TXP5ciML1qjLdsX21BFaFCPsnLbVDphbw1DMMwTggWR3VFDaPZpJ9cjjc+Re1noW8xpM7LqSrJsTfljJDwgohp6IW6UyNVLzGMIe4KE5HNHG+xkaX9XYqUPXdi7m2w6KlizIu1rEocZ+fblIdXpMTSfmPUquiNzsh+J5FETByWlsVoOmaw2VSlMLaaKo4jBm05nePQc882SLErJbBJdyqCzuegIMuN1Vu20CE2UacAJ4Rjq+Gr1h0WZaRNU1z9xI6uEmKhIA=
  app: quiet-river-43350
  on:
    repo: SanDiegoCasey/groceryCompanion
