language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: zPijRWiCsv5Xv3DMsEGtqCUjhzZplEhhoGvKEluuAqi6rY24U9VsJCkoOms6/fTYQWKb9p0Z5eGJewpIG2jXJfVhpPKAvQe1c289scZFKWIMJ9+86LdPVGuxn58eQrQsmirWPeEN1LoQOCICGxcQfCarVTlXMWc+OF25B0Ys4JkV3uQ7PKsPG2ovum1XtMISOqajuUGcg4x7d1G6Dzoy7gCgSBS4VU+1gvZLZBpE9dKvj1e8PSUD0x/mYc38TDOfQdvHXJkCkuHeC2c/HyQgQtBu/nZYQEYsD0c0pyIzR83fDCX30r/n3BIK0Om3ukkla14vuY2lP/raXOMoYZzlJQX3P1r3E2rEl8mvILDJ539TnRYahZS9PwRgTyF4nvYarg/1PlhescMvIooVDIqRpiz06TW5h/0AFxR9eZ5H4cXHUmkMoenE4NgV8g4V3Kw+Aqfdx79a7NIgPGu/nPxU7ukX6Yp8K3Vc8SC9tCxV1HZ/eQTUYWwX8WMKZKzXc5/uqwEh53r2sZEZfLBx6GCiujDJJh7ChV+fzS60RSZP2OZVxsMd8UUU33B1sEReqp1+9DBIXH8q8k/ebIrV36LWmaJU+UGf7YHRcF4bEfpnATdPE8NaAcDIvfqLm6RbFLNMkco91BSesd1HmaipUwx9vH9E3gZcu08JVNSAhRXvRDk=
  app: grocerycompanion
  on:
    repo: SanDiegoCasey/groceryCompanion
